const ingredients = [{ id: 1, name: "chicken", isAlwaysAvailable: false },
{ id: 2, name: "beef", isAlwaysAvailable: false },
{ id: 3, name: "lamb", isAlwaysAvailable: false },
{ id: 4, name: "shrimp", isAlwaysAvailable: false },
{ id: 5, name: "fish", isAlwaysAvailable: false },
{ id: 6, name: "crab", isAlwaysAvailable: false },
{ id: 7, name: "chicken breast", isAlwaysAvailable: false },
{ id: 8, name: "chicken wings", isAlwaysAvailable: false },
{ id: 9, name: "parmesan cheese", isAlwaysAvailable: false },
{ id: 10, name: "eggs", isAlwaysAvailable: false },
{ id: 11, name: "bak choy", isAlwaysAvailable: false },
{ id: 12, name: "basil", isAlwaysAvailable: false },
{ id: 13, name: "black pepper", isAlwaysAvailable: false },
{ id: 14, name: "all-purpose flour", isAlwaysAvailable: false },
{ id: 15, name: "olive oil", isAlwaysAvailable: false },
{ id: 16, name: "salt", isAlwaysAvailable: true },
{ id: 17, name: "tomato sauce", isAlwaysAvailable: true },
{ id: 18, name: "mozarella cheese", isAlwaysAvailable: false },
{ id: 19, name: "water", isAlwaysAvailable: true },
{ id: 20, name: "potato", isAlwaysAvailable: false },
{ id: 21, name: "carrot", isAlwaysAvailable: false },
{ id: 22, name: "onion", isAlwaysAvailable: true },
{ id: 23, name: "garlic", isAlwaysAvailable: true },
{ id: 24, name: "rosemary", isAlwaysAvailable: false },
{ id: 25, name: "parsley", isAlwaysAvailable: false },
{ id: 26, name: "lime juice", isAlwaysAvailable: false },
{ id: 27, name: "mojito marinade", isAlwaysAvailable: false },
{ id: 28, name: "mint sprigs", isAlwaysAvailable: false },
{ id: 29, name: "bread crumbs", isAlwaysAvailable: false },
{ id: 30, name: "cooking oil", isAlwaysAvailable: true },
{ id: 31, name: "red chilli", isAlwaysAvailable: false },
{ id: 32, name: "cabbage", isAlwaysAvailable: false },
{ id: 33, name: "wine", isAlwaysAvailable: false },
{ id: 34, name: "sesame oil", isAlwaysAvailable: true },
{ id: 35, name: "green beans", isAlwaysAvailable: false },
{ id: 36, name: "rice", isAlwaysAvailable: false }]

export function getIngredients(){
    return ingredients
}